server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  profiles:
    active: prod
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/everkan

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: username
    password: password
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


app:
  email-address: "hello@everkan.com"