export const boardConstants = {
  CARD_MOVED: 'CARD_MOVED',
  BOARD_UPDATED: 'BOARD_UPDATED',
  COLUMN_MOVED: 'COLUMN_MOVED',
  UPDATE_BOARD_FAILED: 'UPDATE_BOARD_FAILED',
  FETCH_BOARD_COMPLETED: 'FETCH_BOARD_COMPLETED',
};